# Generated by Django 3.2.12 on 2022-07-21 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vac_reaction',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=32)),
                ('existingComorbidites', models.CharField(blank=True, max_length=300, null=True)),
                ('reaction', models.CharField(blank=True, max_length=300, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
