# Generated by Django 3.2.12 on 2022-07-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_comorb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vac_reaction',
            new_name='Student_reaction',
        ),
    ]
